services:
  app:
    container_name: golang-api
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=golang-postgres-db
      - DB_USER=postgres
      - DB_PASSWORD=sa
      - DB_NAME=potato-module-db
      - DB_PORT=5432
      - MODE=prod

  db:    
    container_name: golang-postgres-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: potato-module-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: